#!/usr/bin/env bash

nick="$1"
mesg="$2"
ircd="$3"
netw="$4"
chan="$5"
self="$6"

read -r cmd extra <<< "$mesg"
if [[ "$mesg" =~ .*\>.+ ]]; then
    read -r nicks <<< "${extra#*>}"
    read -r extra <<< "${extra%>*}"
fi

if [[ "$nicks" == "@all" ]]; then
    printf -- "/names %s\n" "$chan"
    nicks=""
    while test -z "$nicks"; do # wait for the response
        nicks="$(tail -n2 "$ircd/$netw/out" | grep "[[:digit:]-]\+ [[:digit:]:]\+ = $chan" | cut -d" " -f5-)"
        sleep .5
    done
fi

commands=(
  list
  calc
  url
  meurt
)

case "$cmd" in
    list)
	[[ -n "$nicks" ]] && printf -- "%s: %s \n" "$nicks" "${commands[*]}" || printf -- "%s: %s \n" "$nick" "${commands[*]}" ;;

    calc)
        [[ -n "$extra" ]] && . ./modules/calc.sh "$extra" ;;
    url)
        . ./modules/url.sh "$extra" ;;
    meurt)
        . ./modules/meurt.sh "$nick" ;;
    *)
        printf -- "Je ne connais pas cette commande. Essayez :list pour connaitre toutes les commandes disponibles. \n" ;;
esac
